repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.1
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.3.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
